"use client";

import { useParams } from "next/navigation";
import { useAuth } from "@/lib/auth/auth";
import { useInstitutionBySlug } from "@/lib/storage/institutions";
import { useTheme } from "@/contexts/theme-context";
import { useLang } from "@/contexts/language-context";
import { AdmitCardsPage } from "@/components/admit-card/admit-cards-page";
import { Lock, FileCheck } from "lucide-react";

/**
 * One institution's admit-card downloads — `/i/[slug]/admit-cards`.
 *
 * Access is two-layered:
 *   1. the layout only lets an INSTITUTION_ADMIN whose institution matches
 *      the slug in (super admins pass too);
 *   2. the page itself also requires the super-admin permission
 *      (`institutions.allow_admit_card_download`, migration 0033) — RLS
 *      denies the rows anyway, this is the visible half of the same rule.
 *
 * Cards are generated by the super admin; this page only lists, previews,
 * prints and downloads them for its own institution.
 */
export default function InstitutionAdmitCardsPage() {
  const params = useParams();
  const slug = params.institutionSlug as string;
  const { user, loading: authLoading } = useAuth();
  const { theme } = useTheme();
  const { lang: language } = useLang();
  const isDark = theme === "dark";
  const isBn = language === "bn";
  const bi = (bn: string, en: string) => (isBn ? bn : en);

  const { data: inst, isLoading } = useInstitutionBySlug(slug);

  const isSuper = user?.role === "SUPER_ADMIN";
  const loading = authLoading || isLoading;

  if (loading) {
    return (
      <div className={`min-h-screen ${isDark ? "bg-[#0a0a0b]" : "bg-zinc-50"} flex items-center justify-center`}>
        <div className={`h-8 w-8 animate-spin rounded-full border-2 ${isDark ? "border-white/15 border-t-white" : "border-zinc-200 border-t-zinc-900"}`} />
      </div>
    );
  }

  if (!inst) {
    return (
      <div className={`min-h-screen ${isDark ? "bg-[#0a0a0b]" : "bg-zinc-50"} flex items-center justify-center px-6`}>
        <p className={`text-sm ${isDark ? "text-zinc-400" : "text-zinc-500"}`}>
          {bi("প্রতিষ্ঠান পাওয়া যায়নি", "Institution not found")}
        </p>
      </div>
    );
  }

  // Permission not granted → same rule the database enforces, shown as a panel.
  if (!isSuper && !inst.allowAdmitCardDownload) {
    return (
      <div className={`min-h-screen ${isDark ? "bg-[#0a0a0b]" : "bg-zinc-50"}`}>
        <div className="max-w-[1600px] mx-auto p-6 lg:p-8">
          <div className="mb-8">
            <h1 className={`text-2xl font-bold tracking-tight ${isDark ? "text-white" : "text-zinc-900"}`}>
              {bi("প্রবেশপত্র", "Admit Cards")}
            </h1>
          </div>
          <div
            className={`flex flex-col items-center justify-center py-20 px-6 rounded-md border ${
              isDark
                ? "bg-[#141416] border-white/[0.06]"
                : "bg-white border-zinc-200 shadow-sm"
            }`}
          >
            <div
              className={`h-14 w-14 rounded-md flex items-center justify-center mb-4 ${
                isDark ? "bg-white/[0.08]" : "bg-zinc-100"
              }`}
            >
              <Lock className={`h-7 w-7 ${isDark ? "text-zinc-400" : "text-zinc-500"}`} />
            </div>
            <p className={`text-sm font-medium ${isDark ? "text-white" : "text-zinc-900"}`}>
              {bi(
                "প্রবেশপত্র ডাউনলোডের অনুমতি নেই",
                "Admit card download is not permitted yet"
              )}
            </p>
            <p
              className={`text-xs mt-1.5 text-center max-w-md ${isDark ? "text-zinc-500" : "text-zinc-400"}`}
            >
              {bi(
                "সংগ্রয় (সুপার অ্যাডমিন) আপনার প্রতিষ্ঠানের জন্য প্রবেশপত্রের অনুমতি চালু করলে এখানে আপনার নিজের প্রবেশপত্র দেখতে ও ডাউনলোড করতে পারবেন। অনুগ্রহ করে সংগ্রয়ের সাথে যোগাযোগ করুন।",
                "Once the association (super admin) enables admit card access for your institution, your own cards will appear here for preview and download. Please contact the association."
              )}
            </p>
            <div className={`mt-5 flex items-center gap-2 text-[11px] ${isDark ? "text-zinc-500" : "text-zinc-400"}`}>
              <FileCheck className="h-3.5 w-3.5" />
              {inst.nameEn || inst.name}
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Granted (or super admin previewing this institution's page).
  return <AdmitCardsPage mode="institution" institutionId={inst.id} />;
}
